/**
 * Short-lived admin connections to the Postgres CLUSTER (issue #344, epic #339).
 *
 * WHY THIS EXISTS AT ALL, and why it cannot be Prisma:
 *
 * The restore swap renames the live database. `ALTER DATABASE … RENAME TO …`
 * fails while ANY session is connected to the database being renamed, and a
 * session cannot rename the database it is itself connected to. So the rename
 * — and the `CREATE DATABASE`/`DROP DATABASE`/`pg_terminate_backend` around it
 * — must run over a connection to a DIFFERENT database in the same cluster,
 * conventionally the `postgres` maintenance database.
 *
 * Prisma's client is bound to one datasource URL and holds a POOL. Both facts
 * disqualify it here: the pool is precisely the set of connections that has to
 * be gone before the rename can succeed, and `CREATE DATABASE` cannot run
 * inside the implicit transaction Prisma wraps some paths in. A raw `pg.Client`
 * — one connection, opened for a handful of statements and closed immediately —
 * is the right tool, and keeping it OUT of the Prisma pool is the point rather
 * than an incidental detail.
 *
 * IDENTIFIER SAFETY: every database name reaching a statement here goes through
 * {@link quoteIdentifier}, which validates against a strict allowlist BEFORE
 * quoting. Database names cannot be passed as bind parameters in DDL, so the
 * usual parameterised-query defence is unavailable; the allowlist is what
 * stands in for it. Names are generated server-side (`memoriahub_restore_<ts>`)
 * and never taken from a request body, so this is defence in depth — but a
 * future caller passing a name through must still be safe.
 */

import { Client } from 'pg';

import type { PgConnectionConfig } from './pg-dump.util';

/** The maintenance database renames are issued from. Overridable for odd clusters. */
export function resolveMaintenanceDatabase(
  envValue: string | undefined = process.env.PG_MAINTENANCE_DB,
): string {
  const trimmed = (envValue ?? '').trim();
  return trimmed || 'postgres';
}

// ---------------------------------------------------------------------------
// Client factory seam (test-only)
// ---------------------------------------------------------------------------

/** The narrow slice of `pg.Client` this module uses. */
export interface AdminClientLike {
  connect(): Promise<void>;
  query<T = any>(text: string, values?: unknown[]): Promise<{ rows: T[] }>;
  end(): Promise<void>;
}

export interface AdminClientConfig {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
  connectionTimeoutMillis?: number;
  statement_timeout?: number;
}

export type AdminClientFactory = (cfg: AdminClientConfig) => AdminClientLike;

const realFactory: AdminClientFactory = (cfg) =>
  new Client(cfg) as unknown as AdminClientLike;

let clientFactory: AdminClientFactory = realFactory;

/**
 * TEST-ONLY seam mirroring `pg-dump.util.ts`'s `__setSpawnForTests`. Pass `null`
 * to restore the real `pg.Client`. Production code must never call this.
 *
 * The restore state machine is unit-tested with this factory and `spawn` both
 * mocked, which is what makes it testable at all in an environment with no
 * Postgres — see `database-restore.service.spec.ts`.
 */
export function __setAdminClientFactoryForTests(
  factory: AdminClientFactory | null,
): void {
  clientFactory = factory ?? realFactory;
}

// ---------------------------------------------------------------------------
// Identifier quoting
// ---------------------------------------------------------------------------

/** Postgres identifiers are capped at 63 bytes; longer names are silently truncated. */
export const MAX_IDENTIFIER_LENGTH = 63;

const SAFE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

/**
 * Validate and double-quote a database identifier for interpolation into DDL.
 *
 * Rejects anything outside `[A-Za-z_][A-Za-z0-9_]*` rather than escaping it:
 * a legal-but-exotic name (embedded quotes, spaces, unicode) has no business
 * being generated by this feature, so refusing is both safer and a clearer
 * signal that something upstream is wrong.
 */
export function quoteIdentifier(name: string): string {
  if (!name || !SAFE_IDENTIFIER.test(name)) {
    throw new Error(`Unsafe database identifier: ${JSON.stringify(name)}`);
  }
  if (name.length > MAX_IDENTIFIER_LENGTH) {
    throw new Error(
      `Database identifier exceeds ${MAX_IDENTIFIER_LENGTH} bytes: ${name}`,
    );
  }
  return `"${name}"`;
}

// ---------------------------------------------------------------------------
// Connection helper
// ---------------------------------------------------------------------------

export interface AdminConnectionOptions {
  /** Database to connect to. Defaults to the maintenance database. */
  database?: string;
  connectTimeoutMs?: number;
  /**
   * Per-statement timeout. Deliberately UNSET (0 = no limit) by default: the
   * one long statement here is `CREATE DATABASE`, and a timeout that fires
   * mid-DDL buys nothing but ambiguity about whether it landed.
   */
  statementTimeoutMs?: number;
}

const DEFAULT_CONNECT_TIMEOUT_MS = 10_000;

/**
 * Open a single connection, run `fn`, and ALWAYS close it.
 *
 * The `finally` is load-bearing rather than hygiene: a leaked connection to the
 * live database is exactly what makes the subsequent `ALTER DATABASE … RENAME`
 * fail, so the one thing this helper must never do is outlive its caller.
 */
export async function withAdminConnection<T>(
  cfg: PgConnectionConfig,
  fn: (client: AdminClientLike) => Promise<T>,
  opts: AdminConnectionOptions = {},
): Promise<T> {
  const client = clientFactory({
    host: cfg.host,
    port: cfg.port,
    user: cfg.user,
    password: cfg.password,
    database: opts.database ?? resolveMaintenanceDatabase(),
    connectionTimeoutMillis: opts.connectTimeoutMs ?? DEFAULT_CONNECT_TIMEOUT_MS,
    statement_timeout: opts.statementTimeoutMs ?? 0,
  });

  await client.connect();
  try {
    return await fn(client);
  } finally {
    try {
      await client.end();
    } catch {
      // A close failure cannot be acted on and must not mask the real result.
    }
  }
}

// ---------------------------------------------------------------------------
// Cluster operations
// ---------------------------------------------------------------------------

/**
 * PROBE the connecting role's `CREATEDB` privilege — never assume it.
 *
 * Postgres is not part of `base.compose.yml`, so a deployment may be pointed at
 * managed Postgres (RDS, Cloud SQL, Neon, Supabase) where the application role
 * routinely CANNOT create databases. Discovering that by watching
 * `CREATE DATABASE` fail is discovering it too late to offer the admin an
 * alternative; discovering it in pre-flight is what routes them to the guided
 * restore instead. A superuser implicitly has the privilege.
 */
export async function probeCreateDatabasePrivilege(
  client: AdminClientLike,
): Promise<boolean> {
  const res = await client.query<{ rolcreatedb: boolean; rolsuper: boolean }>(
    'SELECT rolcreatedb, rolsuper FROM pg_roles WHERE rolname = current_user',
  );
  const row = res.rows[0];
  if (!row) return false;
  return Boolean(row.rolcreatedb || row.rolsuper);
}

/**
 * True when the `vector` extension is INSTALLABLE in this cluster.
 *
 * The archive contains `CREATE EXTENSION vector` (this schema has three pgvector
 * columns), so restoring into a vanilla `postgres` image fails partway through
 * — after minutes or hours of table loading. `pg_available_extensions` answers
 * the question in milliseconds, before anything has been created.
 */
export async function probePgvectorAvailable(
  client: AdminClientLike,
): Promise<boolean> {
  const res = await client.query<{ ok: boolean }>(
    "SELECT EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'vector') AS ok",
  );
  return Boolean(res.rows[0]?.ok);
}

/** `pg_database_size(<db>)` in bytes — the basis for the disk pre-flight. */
export async function readDatabaseSizeBytes(
  client: AdminClientLike,
  database: string,
): Promise<bigint> {
  const res = await client.query<{ size: string }>(
    'SELECT pg_database_size($1)::text AS size',
    [database],
  );
  return BigInt(res.rows[0]?.size ?? '0');
}

/** `SHOW data_directory` — statfs target for the disk check. Null without permission. */
export async function readDataDirectory(
  client: AdminClientLike,
): Promise<string | null> {
  try {
    const res = await client.query<{ data_directory: string }>(
      'SHOW data_directory',
    );
    return res.rows[0]?.data_directory ?? null;
  } catch {
    // Non-superusers cannot read this GUC on many managed providers.
    return null;
  }
}

export async function databaseExists(
  client: AdminClientLike,
  database: string,
): Promise<boolean> {
  const res = await client.query<{ ok: boolean }>(
    'SELECT EXISTS (SELECT 1 FROM pg_database WHERE datname = $1) AS ok',
    [database],
  );
  return Boolean(res.rows[0]?.ok);
}

/**
 * Count DISTINCT client addresses connected to `database`.
 *
 * This is the multi-replica warning's only available signal. It is a heuristic
 * and is honest about that: two replicas behind one NAT share an address and
 * read as one, and a single replica plus an admin's psql reads as two. It is
 * still worth having — the swap assumes ONE API replica (issue #344's
 * single-replica constraint), and a WARNING that turns out to be a stray psql
 * is far cheaper than silently terminating another replica's in-flight
 * requests mid-rename.
 */
export async function countDistinctClientAddresses(
  client: AdminClientLike,
  database: string,
): Promise<number> {
  const res = await client.query<{ count: string }>(
    `SELECT count(DISTINCT client_addr)::text AS count
       FROM pg_stat_activity
      WHERE datname = $1 AND client_addr IS NOT NULL`,
    [database],
  );
  return Number(res.rows[0]?.count ?? '0');
}

export async function createDatabase(
  client: AdminClientLike,
  database: string,
): Promise<void> {
  await client.query(`CREATE DATABASE ${quoteIdentifier(database)}`);
}

/**
 * Drop a database, tolerating its absence.
 *
 * `WITH (FORCE)` (Postgres 13+) terminates lingering sessions rather than
 * failing — the scratch database being cleaned up after a failed restore can
 * still hold a `pg_restore` worker's dying connection, and a cleanup that
 * fails because of that would leave exactly the orphaned database this exists
 * to prevent.
 */
export async function dropDatabase(
  client: AdminClientLike,
  database: string,
): Promise<void> {
  await client.query(
    `DROP DATABASE IF EXISTS ${quoteIdentifier(database)} WITH (FORCE)`,
  );
}

/**
 * Terminate every OTHER backend connected to `database`.
 *
 * `pid <> pg_backend_pid()` keeps this very connection alive; it is connected
 * to the maintenance database anyway, but the guard is standard and cheap.
 * Returns the number of backends signalled — useful in the audit log as "how
 * much traffic was actually cut off at the swap".
 */
export async function terminateConnections(
  client: AdminClientLike,
  database: string,
): Promise<number> {
  const res = await client.query<{ pid: number }>(
    `SELECT pg_terminate_backend(pid) AS pid
       FROM pg_stat_activity
      WHERE datname = $1 AND pid <> pg_backend_pid()`,
    [database],
  );
  return res.rows.length;
}

/** `ALTER DATABASE <from> RENAME TO <to>` — the swap primitive. Seconds, not hours. */
export async function renameDatabase(
  client: AdminClientLike,
  from: string,
  to: string,
): Promise<void> {
  await client.query(
    `ALTER DATABASE ${quoteIdentifier(from)} RENAME TO ${quoteIdentifier(to)}`,
  );
}

// ---------------------------------------------------------------------------
// Scratch / old database naming
// ---------------------------------------------------------------------------

/**
 * `<live>_restore_<yyyymmddhhmmss>` / `<live>_old_<yyyymmddhhmmss>`, truncated
 * so the result always fits Postgres' 63-byte identifier limit.
 *
 * The shared timestamp suffix is what ties a restore's three databases together
 * in a `\l` listing during an incident, which is the moment the naming has to
 * be self-explanatory.
 */
export function buildSuffix(now: Date = new Date()): string {
  return now.toISOString().replace(/[-:T]/g, '').replace(/\..*$/, '');
}

export function buildScratchDatabaseName(liveDb: string, suffix: string): string {
  return joinWithinLimit(liveDb, `_restore_${suffix}`);
}

export function buildOldDatabaseName(liveDb: string, suffix: string): string {
  return joinWithinLimit(liveDb, `_old_${suffix}`);
}

/**
 * Join `base + tail`, trimming the BASE (never the tail) to fit 63 bytes.
 *
 * Postgres silently truncates an over-long identifier itself, which would make
 * two long-named restores collide on the same physical name while the app still
 * believed they were distinct. Trimming the base rather than the whole string
 * keeps two properties that both matter: the `_restore_<timestamp>` tail — the
 * part that actually disambiguates — survives intact, and the result still
 * starts with the base's first character, so it remains a legal identifier
 * (slicing off the front could leave a leading digit, which is not).
 */
function joinWithinLimit(base: string, tail: string): string {
  const room = MAX_IDENTIFIER_LENGTH - tail.length;
  const trimmedBase = base.length > room ? base.slice(0, Math.max(1, room)) : base;
  return `${trimmedBase}${tail}`;
}
