-- Memories (epic #300, issue #301): persisted, pre-generated memory
-- collections (Memory) plus their member items (MemoryItem) and per-user
-- state (MemoryUserState). See docs/specs/memories.md for the full design.
--
-- NOTE: this file is a hand-pruned version of what `prisma migrate dev`
-- generated. The raw autogenerated diff also proposed dropping the
-- `media_visual_embedding` table, dropping the `faces`/`media_item_embedding`
-- HNSW indexes, dropping `id`/`updated_at` column defaults, and renaming
-- several long-standing foreign key constraints. None of that is related to
-- this migration — it is pre-existing drift between hand-authored raw SQL in
-- earlier migrations (documented in CLAUDE.md/schema.prisma as intentionally
-- not representable in the Prisma schema DSL, e.g. partial HNSW indexes and
-- the `media_visual_embedding` table itself) and what Prisma's diff engine
-- can see from schema.prisma alone. Those statements were stripped from this
-- file so this migration only ever adds the new Memories tables.

-- CreateEnum
CREATE TYPE "MemoryType" AS ENUM ('on_this_day', 'trip', 'person_highlights', 'person_over_years', 'theme', 'seasonal', 'year_in_review');

-- CreateTable
CREATE TABLE "memories" (
    "id" UUID NOT NULL,
    "circle_id" UUID NOT NULL,
    "type" "MemoryType" NOT NULL,
    "period_key" TEXT NOT NULL,
    "subject_key" TEXT NOT NULL DEFAULT '',
    "person_id" UUID,
    "title" TEXT NOT NULL,
    "subtitle" TEXT,
    "narrative" TEXT,
    "title_source" TEXT NOT NULL,
    "title_model" TEXT,
    "cover_media_item_id" UUID,
    "period_start" TIMESTAMPTZ NOT NULL,
    "period_end" TIMESTAMPTZ NOT NULL,
    "item_count" INTEGER NOT NULL,
    "meta" JSONB,
    "generated_at" TIMESTAMPTZ NOT NULL,
    "refreshed_at" TIMESTAMPTZ NOT NULL,
    "expires_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "memories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memory_items" (
    "id" UUID NOT NULL,
    "memory_id" UUID NOT NULL,
    "media_item_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "score" DOUBLE PRECISION,

    CONSTRAINT "memory_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memory_user_state" (
    "id" UUID NOT NULL,
    "memory_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "seen_at" TIMESTAMPTZ,
    "hidden_at" TIMESTAMPTZ,
    "favorited_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "memory_user_state_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "memories_circle_id_deleted_at_expires_at_generated_at_idx" ON "memories"("circle_id", "deleted_at", "expires_at", "generated_at" DESC);

-- CreateIndex
CREATE INDEX "memories_circle_id_type_idx" ON "memories"("circle_id", "type");

-- CreateIndex
CREATE INDEX "memories_person_id_idx" ON "memories"("person_id");

-- CreateIndex
CREATE INDEX "memories_cover_media_item_id_idx" ON "memories"("cover_media_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "memories_circle_id_type_period_key_subject_key_key" ON "memories"("circle_id", "type", "period_key", "subject_key");

-- CreateIndex
CREATE INDEX "memory_items_memory_id_position_idx" ON "memory_items"("memory_id", "position");

-- CreateIndex
CREATE INDEX "memory_items_media_item_id_idx" ON "memory_items"("media_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "memory_items_memory_id_media_item_id_key" ON "memory_items"("memory_id", "media_item_id");

-- CreateIndex
CREATE INDEX "memory_user_state_user_id_favorited_at_idx" ON "memory_user_state"("user_id", "favorited_at");

-- CreateIndex
CREATE UNIQUE INDEX "memory_user_state_memory_id_user_id_key" ON "memory_user_state"("memory_id", "user_id");

-- AddForeignKey
ALTER TABLE "memories" ADD CONSTRAINT "memories_circle_id_fkey" FOREIGN KEY ("circle_id") REFERENCES "circles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memories" ADD CONSTRAINT "memories_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memories" ADD CONSTRAINT "memories_cover_media_item_id_fkey" FOREIGN KEY ("cover_media_item_id") REFERENCES "media_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_memory_id_fkey" FOREIGN KEY ("memory_id") REFERENCES "memories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_items" ADD CONSTRAINT "memory_items_media_item_id_fkey" FOREIGN KEY ("media_item_id") REFERENCES "media_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_user_state" ADD CONSTRAINT "memory_user_state_memory_id_fkey" FOREIGN KEY ("memory_id") REFERENCES "memories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memory_user_state" ADD CONSTRAINT "memory_user_state_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
