/**
 * Unit tests — thumbnail-key.util (issue #434)
 *
 * Pins the two properties the stale-thumbnail fix rests on:
 *   1. the key is VERSIONED, so regenerated bytes never reuse a URL that a
 *      browser/CDN was told to cache as `immutable` for a year;
 *   2. the server-side version is CONTENT-ADDRESSED, so an ordinary reprocess
 *      of unchanged bytes reuses the same key and stays an idempotent upsert
 *      (no key churn, no needless cache invalidation, no orphan to prune).
 */
import {
  THUMBNAIL_KEY_PREFIX,
  buildThumbnailKey,
  randomThumbnailVersion,
  thumbnailKeyPrefixFor,
  thumbnailVersionFromBytes,
} from './thumbnail-key.util';

describe('thumbnail-key.util', () => {
  describe('buildThumbnailKey', () => {
    it('produces thumbnails/<objectId>-<version>.jpg', () => {
      expect(buildThumbnailKey('obj-1', 'abc123')).toBe('thumbnails/obj-1-abc123.jpg');
    });

    it('never produces the legacy content-independent thumbnails/<objectId>.jpg key', () => {
      const key = buildThumbnailKey('obj-1', thumbnailVersionFromBytes(Buffer.from('x')));
      expect(key).not.toBe('thumbnails/obj-1.jpg');
    });

    it('stays under the thumbnails/ prefix the recursion guards key off', () => {
      expect(buildThumbnailKey('obj-1', 'v').startsWith(THUMBNAIL_KEY_PREFIX)).toBe(true);
    });
  });

  describe('thumbnailVersionFromBytes', () => {
    it('is a 16-char lowercase hex token', () => {
      expect(thumbnailVersionFromBytes(Buffer.from('some-jpeg-bytes'))).toMatch(
        /^[0-9a-f]{16}$/,
      );
    });

    it('is stable for identical bytes — an unchanged reprocess reuses the same key', () => {
      const a = thumbnailVersionFromBytes(Buffer.from('same-bytes'));
      const b = thumbnailVersionFromBytes(Buffer.from('same-bytes'));
      expect(a).toBe(b);
    });

    it('changes when the bytes change — the destructive-overwrite case', () => {
      const before = thumbnailVersionFromBytes(Buffer.from('original-thumb'));
      const after = thumbnailVersionFromBytes(Buffer.from('enhanced-thumb'));
      expect(after).not.toBe(before);
    });

    it('differs even for a one-byte difference', () => {
      expect(thumbnailVersionFromBytes(Buffer.from([1, 2, 3]))).not.toBe(
        thumbnailVersionFromBytes(Buffer.from([1, 2, 4])),
      );
    });
  });

  describe('randomThumbnailVersion', () => {
    it('is a 16-char lowercase hex token, matching the content-addressed shape', () => {
      expect(randomThumbnailVersion()).toMatch(/^[0-9a-f]{16}$/);
    });

    it('differs across calls — the node path must never reuse a key', () => {
      const tokens = new Set(Array.from({ length: 50 }, () => randomThumbnailVersion()));
      expect(tokens.size).toBe(50);
    });
  });

  describe('thumbnailKeyPrefixFor', () => {
    it('matches BOTH the legacy unversioned key and every versioned key for that object', () => {
      const prefix = thumbnailKeyPrefixFor('obj-1');
      expect('thumbnails/obj-1.jpg'.startsWith(prefix)).toBe(true);
      expect(buildThumbnailKey('obj-1', 'deadbeefdeadbeef').startsWith(prefix)).toBe(true);
    });

    it('does not match another object id', () => {
      expect('thumbnails/obj-2-abc.jpg'.startsWith(thumbnailKeyPrefixFor('obj-1'))).toBe(
        false,
      );
    });
  });
});
