package memoriahub.marin.cr.mediasync

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory

class MediaSyncShortcutsTest {
    @Test fun `no dynamic shortcuts until paired`() {
        assertTrue(MediaSyncShortcuts.dynamic(paired = false, paused = false).isEmpty())
    }

    @Test fun `sync now and pause while running`() {
        val list = MediaSyncShortcuts.dynamic(paired = true, paused = false, scheme = "memoriahub")
        assertEquals(listOf("Sync now", "Pause sync"), list.map { it.shortLabel })
        assertEquals(listOf("memoriahub://media-sync?action=sync", "memoriahub://media-sync?action=pause"), list.map { it.uri })
        assertEquals(listOf(MediaSyncShortcuts.SYNC_NOW, MediaSyncShortcuts.PAUSE_RESUME), list.map { it.id })
    }

    @Test fun `resume replaces pause while paused`() {
        val toggle = MediaSyncShortcuts.dynamic(paired = true, paused = true, scheme = "memoriahub").last()
        assertEquals("Resume sync", toggle.shortLabel)
        assertEquals("memoriahub://media-sync?action=resume", toggle.uri)
        assertEquals(MediaSyncShortcuts.PAUSE_RESUME, toggle.id)
    }

    @Test fun `short labels fit the launcher`() {
        for (s in MediaSyncShortcuts.dynamic(paired = true, paused = true) + MediaSyncShortcuts.dynamic(paired = true, paused = false)) {
            assertTrue(s.shortLabel, s.shortLabel.length <= 12)
        }
    }
}

/**
 * The static long-press shortcuts generated by `GenerateShortcutsTask` (app/build.gradle.kts):
 * both entries, targeting [MediaSyncActivity] in this variant's package. Reads the generated
 * res/xml/shortcuts.xml of each variant built so far (unit tests run from the module directory,
 * after resource generation for the debug variant).
 */
class GeneratedShortcutsTest {
    private fun generated(variant: String) = File("build/generated/identity/$variant/res/xml/shortcuts.xml")

    @Test fun `debug shortcuts target the media sync activity`() {
        val file = generated("debug")
        assumeTrue("shortcuts.xml not generated yet", file.isFile)
        assertShortcuts(file, "memoriahub.marin.cr.debug")
    }

    @Test fun `release shortcuts target the media sync activity`() {
        val file = generated("release")
        assumeTrue("release resources not generated in this build", file.isFile)
        assertShortcuts(file, "memoriahub.marin.cr")
    }

    @Test fun `every shortcut has its label strings`() {
        val strings = File("src/main/res/values/strings.xml")
        assumeTrue(strings.isFile)
        val text = strings.readText()
        for (id in listOf("media_sync", "diagnostics")) {
            for (suffix in listOf("short", "long", "disabled")) {
                assertTrue("shortcut_${id}_$suffix", text.contains("name=\"shortcut_${id}_$suffix\""))
            }
        }
    }

    private fun assertShortcuts(file: File, expectedPackage: String) {
        val doc = DocumentBuilderFactory.newInstance().apply { isNamespaceAware = true }.newDocumentBuilder().parse(file)
        val android = "http://schemas.android.com/apk/res/android"
        val shortcuts = doc.getElementsByTagName("shortcut")
        val found = (0 until shortcuts.length).associate { i ->
            val el = shortcuts.item(i) as org.w3c.dom.Element
            val intent = el.getElementsByTagName("intent").item(0) as org.w3c.dom.Element
            assertEquals(expectedPackage, intent.getAttributeNS(android, "targetPackage"))
            assertEquals("memoriahub.marin.cr.mediasync.MediaSyncActivity", intent.getAttributeNS(android, "targetClass"))
            assertEquals("android.intent.action.VIEW", intent.getAttributeNS(android, "action"))
            el.getAttributeNS(android, "shortcutId") to intent.getAttributeNS(android, "data")
        }
        assertEquals(
            mapOf("media_sync" to "memoriahub://media-sync", "diagnostics" to "memoriahub://media-sync/diagnostics"),
            found,
        )
    }
}

class MediaSyncFormatTest {
    private val us = java.util.Locale.US

    @Test fun bytes() {
        assertEquals("0 B", MediaSyncFormat.bytes(0, us))
        assertEquals("999 B", MediaSyncFormat.bytes(999, us))
        assertEquals("1.5 KB", MediaSyncFormat.bytes(1_500, us))
        assertEquals("120 MB", MediaSyncFormat.bytes(120_000_000, us))
        assertEquals("2.5 GB", MediaSyncFormat.bytes(2_500_000_000, us))
        assertEquals("0 B", MediaSyncFormat.bytes(-5, us))
    }

    @Test fun durations() {
        assertEquals("now", MediaSyncFormat.inDuration(10_000))
        assertEquals("in 9 min", MediaSyncFormat.inDuration(9 * 60_000))
        assertEquals("in 2 h", MediaSyncFormat.inDuration(90 * 60_000))
        assertEquals("just now", MediaSyncFormat.ago(5_000))
        assertEquals("3 h ago", MediaSyncFormat.ago(3 * 3_600_000L))
        assertEquals("2 days ago", MediaSyncFormat.ago(50 * 3_600_000L))
    }

    @Test fun counts() {
        assertEquals("1 photo", MediaSyncFormat.plural(1, "photo", locale = us))
        assertEquals("1,234 videos", MediaSyncFormat.plural(1234, "video", locale = us))
        assertEquals("No photos or videos", MediaSyncFormat.photosAndVideos(0, 0, us))
        assertEquals(45, MediaSyncFormat.percent(45, 100))
        assertEquals(null, MediaSyncFormat.percent(1, 0))
    }
}
