import { useCallback, useEffect, useState } from 'react';
import { getMemoriesFeed } from '../services/memories';
import { useIsMounted } from './useIsMounted';
import { useMemoryListState } from './useMemoryListState';
import type { MemoryListMutators } from './useMemoryListState';
import type { MemoryFeedCard } from '../types/memories';

export interface UseMemoriesFeedResult
  extends Pick<
    MemoryListMutators<MemoryFeedCard>,
    'patchMyState' | 'removeItem' | 'restoreItem'
  > {
  items: MemoryFeedCard[];
  isLoading: boolean;
  error: string | null;
  refresh: () => Promise<void>;
}

/**
 * Home carousel feed (`GET /api/memories/feed`).
 *
 * Pass `enabled: false` — which the carousel does whenever `features.memories`
 * is not strictly `true` — to keep the hook completely inert: NO request is
 * ever issued, which is the epic's "zero cost when off" requirement expressed
 * on the client. A null `circleId` is inert for the same reason.
 *
 * There is no polling. The feed is regenerated by an hourly cron at most, so a
 * poll would spend requests observing a value that cannot have changed; the
 * carousel refetches on circle switch and on `refresh()` only.
 */
export function useMemoriesFeed(
  circleId: string | null,
  enabled = true,
): UseMemoriesFeedResult {
  const [items, setItems] = useState<MemoryFeedCard[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const isMounted = useIsMounted();
  const { patchMyState, removeItem, restoreItem, clearRemoved } =
    useMemoryListState<MemoryFeedCard>(setItems);

  const active = enabled && circleId != null;

  const load = useCallback(async () => {
    clearRemoved();
    if (!active || !circleId) {
      setItems([]);
      setError(null);
      setIsLoading(false);
      return;
    }
    setIsLoading(true);
    setError(null);
    try {
      const result = await getMemoriesFeed(circleId);
      if (!isMounted()) return;
      setItems(result.items);
    } catch (err) {
      if (!isMounted()) return;
      setItems([]);
      setError(err instanceof Error ? err.message : 'Failed to load memories');
    } finally {
      if (isMounted()) setIsLoading(false);
    }
  }, [active, circleId, isMounted, clearRemoved]);

  useEffect(() => {
    void load();
  }, [load]);

  return {
    items,
    isLoading,
    error,
    refresh: load,
    patchMyState,
    removeItem,
    restoreItem,
  };
}
