# MemoriaHub Production Docker Compose
# Usage: docker compose -f infra/compose/prod.compose.yml up -d
#
# Prerequisites:
# - Copy .env.example to .env and configure all values
# - Set up SSL certificates (or use a reverse proxy like Traefik/Caddy)
# - Configure external DNS

name: memoriahub

services:
  # =============================================================================
  # Core Infrastructure
  # =============================================================================

  postgres:
    image: postgres:16-alpine
    container_name: memoriahub-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 1G

  # Note: For production, consider using AWS S3 or a managed S3-compatible service
  # MinIO is included here for self-hosted deployments
  minio:
    image: minio/minio:latest
    container_name: memoriahub-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 512M

  minio-init:
    image: minio/mc:latest
    container_name: memoriahub-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      mc mb myminio/${S3_BUCKET} --ignore-existing;
      mc anonymous set none myminio/${S3_BUCKET};
      exit 0;
      "
    networks:
      - memoriahub-internal

  # =============================================================================
  # Reverse Proxy
  # =============================================================================

  nginx:
    image: nginx:alpine
    container_name: memoriahub-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/cert.pem:ro
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - api
      - web
    networks:
      - memoriahub-internal
      - memoriahub-external
    deploy:
      resources:
        limits:
          memory: 128M

  # =============================================================================
  # Application Services
  # =============================================================================

  api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
      target: production
    container_name: memoriahub-api
    restart: always
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE:-true}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      OAUTH_GOOGLE_CLIENT_ID: ${OAUTH_GOOGLE_CLIENT_ID}
      OAUTH_GOOGLE_CLIENT_SECRET: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAUTH_MICROSOFT_CLIENT_ID: ${OAUTH_MICROSOFT_CLIENT_ID}
      OAUTH_MICROSOFT_CLIENT_SECRET: ${OAUTH_MICROSOFT_CLIENT_SECRET}
      OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}
      OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: memoriahub-api
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 512M
      replicas: 2

  worker:
    build:
      context: ../../
      dockerfile: apps/worker/Dockerfile
      target: production
    container_name: memoriahub-worker
    restart: always
    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE:-true}
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-4}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: memoriahub-worker
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 1G
      replicas: 2

  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
      target: production
    container_name: memoriahub-web
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 128M

  # =============================================================================
  # Observability Stack
  # =============================================================================

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: memoriahub-jaeger
    restart: always
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
    volumes:
      - jaeger_data:/badger
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 512M

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: memoriahub-prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 512M

  loki:
    image: grafana/loki:2.9.3
    container_name: memoriahub-loki
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../observability/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 512M

  promtail:
    image: grafana/promtail:2.9.3
    container_name: memoriahub-promtail
    restart: always
    volumes:
      - ../observability/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 128M

  grafana:
    image: grafana/grafana:10.2.3
    container_name: memoriahub-grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL:-http://localhost:3001}
    volumes:
      - ../observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - jaeger
    networks:
      - memoriahub-internal
    deploy:
      resources:
        limits:
          memory: 256M

# =============================================================================
# Volumes
# =============================================================================

volumes:
  postgres_data:
    name: memoriahub-postgres-data
  minio_data:
    name: memoriahub-minio-data
  prometheus_data:
    name: memoriahub-prometheus-data
  loki_data:
    name: memoriahub-loki-data
  grafana_data:
    name: memoriahub-grafana-data
  jaeger_data:
    name: memoriahub-jaeger-data

# =============================================================================
# Networks
# =============================================================================

networks:
  memoriahub-internal:
    name: memoriahub-internal
    driver: bridge
    internal: true
  memoriahub-external:
    name: memoriahub-external
    driver: bridge
